name: Deploy dev on Heroku

on: 
  push:
    branches:
      - dev
  pull_request:

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME_DEV -r heroku-dev
        env:
          HEROKU_APP_NAME_DEV: ${{ secrets.HEROKU_APP_NAME_DEV }}
      - name: Pull dev
        run: git pull origin dev
      - name: Git remote
        run: git remote -v
      - name: Git branch
        run: git branch
      - name: Push to Heroku
        run: git push heroku-dev dev:main
