name: Test ESLint

on:
  - pull_request

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:

      # Check out the repository
      - uses: actions/checkout@v3

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 22.20.0

      # Install your dependencies
      - run: npm ci

      # Run ESLint
      - run: yarn lint
